### PR TITLE
Theme about landing match specs

### PR DESCRIPTION
**Pull request by rinilkunhiraman**
Updated Theme.ts
Updated the landing Page
Updated Footer
Landing Page

### CODE REVIEW

**Comment by nopestack** [comment]
@rkr-dev would you please address the pending conflicts with master?

**Comment by thakkery** [comment]
The spacing and text on the home page CTA button seem off. Only the one at the top of the home page. The one at the bottom of the page seems fine. Text in the top button should be centered on the button and preferably a bit larger for readability. Adjusting the main section’s button text will get this up to spec.

**Comment by rinilkunhiraman** [comment]
landing1 1

I haven't made any changes yet. Kindly review this output of my previous commit before I  can work on the conflicts.

**Comment by nopestack** [comment]
@rkr-dev and @Amwam would you please check these conflicts and resolve them?

**Comment by rinilkunhiraman** [comment]
I am on it. I will update it

**Pull request closed without merging**
